version: '3.7'
services:
  bitcoind:
    image: lncm/bitcoind:0.18.0-linux-arm
    entrypoint: bitcoind -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333
    volumes:
      - /media/archive/archive/bitcoin/:/root/.bitcoin/
    restart: always
    network_mode: host

  lnd:
    image: lncm/lnd:0.7.1-neutrino-wt
    volumes:
      - /media/volatile/volatile/lnd/logs:/root/.lnd/logs
      - /media/important/important/lnd/data:/root/.lnd/data
      - /media/important/important/lnd/lnd.conf:/root/.lnd/lnd.conf
      - /media/important/important/lnd:/root/.lnd
      - /var/lib/tor:/var/lib/tor
    depends_on:
      - bitcoind
    restart: on-failure
    network_mode: host

  invoicer:
    image: lncm/invoicer:0.4.0
    volumes:
      - /media/important/important/invoicer:/root/.lncm
      - /media/important/important/lnd:/lnd
      - /home/lncm/public_html:/static
      - /media/volatile/volatile/invoicer:/logs
    depends_on:
      - lnd
    restart: on-failure
    network_mode: host
